[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Jeronimo F. Martinez Sanchez <jms@rz0r.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
